language: node_js
install:
- nvm install stable
- npm install -g ionic
- npm install -g cordova
- npm install -g firebase-tools
script:
- cd ionicapp
- npm install
- ionic build browser
after_success:
- firebase deploy --token ${FIREBASE_TOKEN}